apiVersion: v1
kind: Service
metadata:
  name: lianliankan-backend
  namespace: lianliankan
spec:
  type: ClusterIP
  selector:
    app: lianliankan-backend
  ports:
    - port: 80
      targetPort: 8000
